//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable InconsistentNaming

using System;
using Sitecore.Data;

namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _Settings
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_Settings</para>	
  /// <para>ID: 0e69af35-6bf1-412c-8ecf-d9ea60bc3086</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _Settings
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_Settings
      /// </summary>
      public static readonly ID ID = new ID("{0E69AF35-6BF1-412C-8ECF-D9EA60BC3086}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Last Use field.
        /// <para>Description: </para>
        /// <para>Field Type: Date</para>		
        /// <para>Field ID: 64e091e5-91b4-485e-9f60-48607199197c</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Last_Use
        {
          public static readonly ID ID = new ID("{64E091E5-91B4-485E-9F60-48607199197C}");
          public static readonly string FieldName = "Last Use";
        }
        
        /// <summary>
        /// The Multisites field.
        /// <para>Description: </para>
        /// <para>Field Type: Multilist</para>		
        /// <para>Field ID: 511c6368-8791-4fa8-a6d3-92931b2382d0</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Multisites
        {
          public static readonly ID ID = new ID("{511C6368-8791-4FA8-A6D3-92931B2382D0}");
          public static readonly string FieldName = "Multisites";
        }
        
        /// <summary>
        /// The Redirect Code field.
        /// <para>Description: </para>
        /// <para>Field Type: Integer</para>		
        /// <para>Field ID: acc539ce-79c8-45fd-ab52-5bdf3257c571</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Redirect_Code
        {
          public static readonly ID ID = new ID("{ACC539CE-79C8-45FD-AB52-5BDF3257C571}");
          public static readonly string FieldName = "Redirect Code";
        }
        
        /// <summary>
        /// The Use on default site field.
        /// <para>Description: </para>
        /// <para>Field Type: Checkbox</para>		
        /// <para>Field ID: 7b7a2555-8af5-4dcd-ae4c-ae3929ad38e6</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Use_On_Default_Site
        {
          public static readonly ID ID = new ID("{7B7A2555-8AF5-4DCD-AE4C-AE3929AD38E6}");
          public static readonly string FieldName = "Use on default site";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _RegEx Redirect
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_RegEx Redirect</para>	
  /// <para>ID: 10b4487b-b89a-4f4d-8e8d-2f37e95e4830</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _RegEx_Redirect
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_RegEx Redirect
      /// </summary>
      public static readonly ID ID = new ID("{10B4487B-B89A-4F4D-8E8D-2F37E95E4830}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Expression field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: feb12e97-f138-46e9-b74f-c676a286af2c</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Expression
        {
          public static readonly ID ID = new ID("{FEB12E97-F138-46E9-B74F-C676A286AF2C}");
          public static readonly string FieldName = "Expression";
        }
        
        /// <summary>
        /// The Value field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: c526077b-1253-4e82-8f7f-4752cec3a6e1</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Value
        {
          public static readonly ID ID = new ID("{C526077B-1253-4E82-8F7F-4752CEC3A6E1}");
          public static readonly string FieldName = "Value";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Redirect Manager
  /// <para>Path: /sitecore/templates/Redirect Manager/Redirect Manager</para>	
  /// <para>ID: 2f79e9a8-ce0c-4760-aebf-2100aa56ac67</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Redirect_Manager
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Redirect Manager
      /// </summary>
      public static readonly ID ID = new ID("{2F79E9A8-CE0C-4760-AEBF-2100AA56AC67}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Folder
  /// <para>Path: /sitecore/templates/Redirect Manager/Folder</para>	
  /// <para>ID: 75a8f163-186f-459e-8aff-3d161a94a9c7</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Folder
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Folder
      /// </summary>
      public static readonly ID ID = new ID("{75A8F163-186F-459E-8AFF-3D161A94A9C7}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Section to Section
  /// <para>Path: /sitecore/templates/Redirect Manager/Section to Section</para>	
  /// <para>ID: 77a922ae-c49e-468d-ba7e-91746a34e7e0</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Section_To_Section
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Section to Section
      /// </summary>
      public static readonly ID ID = new ID("{77A922AE-C49E-468D-BA7E-91746A34E7E0}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _Multisite
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_Multisite</para>	
  /// <para>ID: 83abb3c0-40c5-4a33-8a33-be9e81b6eb62</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _Multisite
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_Multisite
      /// </summary>
      public static readonly ID ID = new ID("{83ABB3C0-40C5-4A33-8A33-BE9E81B6EB62}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Multisite Prefix field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: e60a0fb2-5125-4d2b-a8b2-2b8a5ced4a94</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Multisite_Prefix
        {
          public static readonly ID ID = new ID("{E60A0FB2-5125-4D2B-A8B2-2B8A5CED4A94}");
          public static readonly string FieldName = "Multisite Prefix";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _Section to Item
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_Section to Item</para>	
  /// <para>ID: 8bfc5d64-d15c-45c4-b5a0-a42ffc525f26</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _Section_To_Item
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_Section to Item
      /// </summary>
      public static readonly ID ID = new ID("{8BFC5D64-D15C-45C4-B5A0-A42FFC525F26}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Base Section field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 85196b35-3f71-43ae-8498-7865c4d3b64b</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Base_Section
        {
          public static readonly ID ID = new ID("{85196B35-3F71-43AE-8498-7865C4D3B64B}");
          public static readonly string FieldName = "Base Section";
        }
        
        /// <summary>
        /// The Target Item field.
        /// <para>Description: </para>
        /// <para>Field Type: link</para>		
        /// <para>Field ID: a48dfbac-90d3-41c5-a691-cf779eac4744</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Target_Item
        {
          public static readonly ID ID = new ID("{A48DFBAC-90D3-41C5-A691-CF779EAC4744}");
          public static readonly string FieldName = "Target Item";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _Section to Section
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_Section to Section</para>	
  /// <para>ID: 9fdf5133-01ca-4807-98d7-b428cb847947</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _Section_To_Section
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_Section to Section
      /// </summary>
      public static readonly ID ID = new ID("{9FDF5133-01CA-4807-98D7-B428CB847947}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Base Section field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 690ee95d-743f-491e-8b61-6974b5b3c8c2</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Base_Section
        {
          public static readonly ID ID = new ID("{690EE95D-743F-491E-8B61-6974B5B3C8C2}");
          public static readonly string FieldName = "Base Section";
        }
        
        /// <summary>
        /// The Target Section field.
        /// <para>Description: </para>
        /// <para>Field Type: Internal Link</para>		
        /// <para>Field ID: c8aa69e0-75be-4440-83f1-79c961c80ac6</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Target_Section
        {
          public static readonly ID ID = new ID("{C8AA69E0-75BE-4440-83F1-79C961C80AC6}");
          public static readonly string FieldName = "Target Section";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Multisite
  /// <para>Path: /sitecore/templates/Redirect Manager/Multisite</para>	
  /// <para>ID: a77b0208-6fd5-4ff5-beed-a922edb35a90</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Multisite
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Multisite
      /// </summary>
      public static readonly ID ID = new ID("{A77B0208-6FD5-4FF5-BEED-A922EDB35A90}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Section to Item
  /// <para>Path: /sitecore/templates/Redirect Manager/Section to Item</para>	
  /// <para>ID: a7c5e6ab-48ff-4846-9a2c-255f8387f18e</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Section_To_Item
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Section to Item
      /// </summary>
      public static readonly ID ID = new ID("{A7C5E6AB-48FF-4846-9A2C-255F8387F18E}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// _Item to Item
  /// <para>Path: /sitecore/templates/Redirect Manager/Data/_Item to Item</para>	
  /// <para>ID: bcffd681-ec1a-4edb-a0ce-eb005f900a77</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct _Item_To_Item
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Data/_Item to Item
      /// </summary>
      public static readonly ID ID = new ID("{BCFFD681-EC1A-4EDB-A0CE-EB005F900A77}");

      public struct Fields 
      {
        
        /// <summary>
        /// The Base Item field.
        /// <para>Description: </para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 19293c70-f330-454e-8bd8-3cc8c7d35c34</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Base_Item
        {
          public static readonly ID ID = new ID("{19293C70-F330-454E-8BD8-3CC8C7D35C34}");
          public static readonly string FieldName = "Base Item";
        }
        
        /// <summary>
        /// The Target Item field.
        /// <para>Description: </para>
        /// <para>Field Type: link</para>		
        /// <para>Field ID: f8d4bf0c-26ed-49ef-aace-30b4795bf528</para>
        /// <para>Shared: 1</para>
        /// <para>Unversioned: </para>
        /// <para>Default Value: </para>
        /// </summary>
        public struct Target_Item
        {
          public static readonly ID ID = new ID("{F8D4BF0C-26ED-49EF-AACE-30B4795BF528}");
          public static readonly string FieldName = "Target Item";
        }
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// Item to Item
  /// <para>Path: /sitecore/templates/Redirect Manager/Item to Item</para>	
  /// <para>ID: d0bffa7b-ca51-400d-9037-809decfb14d3</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct Item_To_Item
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/Item to Item
      /// </summary>
      public static readonly ID ID = new ID("{D0BFFA7B-CA51-400D-9037-809DECFB14D3}");

      public struct Fields 
      {
      }
    }
  }
}
namespace Sitecore.Foundation.RedirectManager
{
  /// <summary>
  /// RegEx Redirect
  /// <para>Path: /sitecore/templates/Redirect Manager/RegEx Redirect</para>	
  /// <para>ID: f91102d6-c17e-4966-9a1a-f551fdd18d40</para>	
  /// </summary>
  public partial struct Templates
  {
    public struct RegEx_Redirect
    {
      /// <summary>
      /// The Template ID for /sitecore/templates/Redirect Manager/RegEx Redirect
      /// </summary>
      public static readonly ID ID = new ID("{F91102D6-C17E-4966-9A1A-F551FDD18D40}");

      public struct Fields 
      {
      }
    }
  }
}
